### ISSUE TITLE
Review for VnV plan for Prof. Spencer Smith

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#10]
My [VnV plan](https://github.com/gordonwky/GMM_EM/blob/b2a240bb5b382ec9ea3b3b35c1c88fcaee2709a8/docs/VnVPlan/CAS741_VnV.pdf]) is here.

**Comment by smiths** [comment]
[KimYing_CAS741_VnV.pdf](https://github.com/gordonwky/GMM_EM/files/14566824/KimYing_CAS741_VnV.pdf)
