### ISSUE TITLE
Review for VnV plan for Domain Expert Xinyu

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#11]
My [VnV plan](https://github.com/gordonwky/GMM_EM/blob/b2a240bb5b382ec9ea3b3b35c1c88fcaee2709a8/docs/VnVPlan/CAS741_VnV.pdf) is here.

**Comment by lele0007** [comment]
I write some comments on the document. 
[CAS741_VnV.pdf](https://github.com/gordonwky/GMM_EM/files/14368417/CAS741_VnV.pdf)

**Comment by gordonwky** [comment]
Problem resolved in the latest version.
