### ISSUE TITLE
MG and MIS Review for Prof. Spencer Smith

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#13]
[MG](https://github.com/gordonwky/GMM_EM/blob/b1ec38bcb6fe5c46b940961f7aaf8e7d34ff641c/docs/Design/SoftArchitecture/CAS741_MG.pdf) is Here. 

[MIS](https://github.com/gordonwky/GMM_EM/blob/b1ec38bcb6fe5c46b940961f7aaf8e7d34ff641c/docs/Design/SoftDetailedDes/CAS741_MIS.pdf) is Here. 

Thank you for your review. Here is my Design document

**Comment by smiths** [comment]
[KimYingCAS741_MG.pdf - PDF Expert.pdf](https://github.com/gordonwky/GMM_EM/files/14846201/KimYingCAS741_MG.pdf.-.PDF.Expert.pdf)
[KimYingCAS741_MIS.pdf - PDF Expert.pdf](https://github.com/gordonwky/GMM_EM/files/14846204/KimYingCAS741_MIS.pdf.-.PDF.Expert.pdf)
