### ISSUE TITLE
Review for Hossain (Second Reviewer)

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#15]
[MG](https://github.com/gordonwky/GMM_EM/blob/b1ec38bcb6fe5c46b940961f7aaf8e7d34ff641c/docs/Design/SoftArchitecture/CAS741_MG.pdf) is Here. 

[MIS](https://github.com/gordonwky/GMM_EM/blob/b1ec38bcb6fe5c46b940961f7aaf8e7d34ff641c/docs/Design/SoftDetailedDes/CAS741_MIS.pdf) is Here. 

Thank you for your review. Here is my Design document

**Comment by XessX** [comment]
Hi! @gordonwky ,
Please, I have checked you MG & MIS. 

Here's the short issues i reviewed for both MG #16 #17 #18 and MIS #19 #20 #21 , respectively. Good luck!

Al

**Comment by gordonwky** [comment]
Problem resolved in the latest version
