### ISSUE TITLE
SRS document review

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#2]
Here is my [SRS Document](https://github.com/gordonwky/GMM_EM/blob/886100bf4d484a3e241207968d7bd1af96f67011/docs/SRS/cas741_SRS.pdf) in PDF format

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[KimYingWong_SRS.pdf](https://github.com/gordonwky/GMM_EM/files/14390282/KimYingWong_SRS.pdf)
