### ISSUE TITLE
MIS Review #2 : Section 6 (Plotting Module)

### ISSUE THREAD

**Issue by XessX** [gordonwky/GMM_EM#20]
The Plotting Module (Section 14) concerns Assumptions as well as the Semantics of its Access Routine. The main aim of the module's Assumptions is minimization and errors. Nonetheless, the absence of specific exceptions, particularly those related to problems within the Module (such as library errors, invalid data ones, and others), is what will lead to potentially better confusion.

Al

**Comment by gordonwky** [comment]
Problem resolved in the latest version
