### ISSUE TITLE
(MG) Problems about AC2 and AC3

### ISSUE THREAD

**Issue by lele0007** [gordonwky/GMM_EM#24]
“AC2: The format of the initial input data.”
“AC3: The format of the input parameters.”
Are the input data and input parameters the same? Whether input data is Parameters Specification Module (M7)? If so, are these parameters input? In M7, it said “the specific parameters are for training module”, they should not be set in the model training module, why are they inputs?

**Comment by gordonwky** [comment]
Problem resolved in the latest version
