### ISSUE TITLE
(MG) Problems about Figure 1 : Use hierarchy among modules

### ISSUE THREAD

**Issue by lele0007** [gordonwky/GMM_EM#29]
1.Does “Control module” equals to “Main module”? 
2.There are some overlapping lines in the picture. For example, the Main module only has connections to “Model Hyper-parameters Initiation Module” and “Model Training Module” or has connections to all other modules.
3.Why is “Sequence Data Structure Module” separated from other modules? Is it not connected to other modules?

**Comment by gordonwky** [comment]
Sequence Data Structure Module is the data structure that applies to every module that possibly uses matrix or array as their variables. So it connects to all modules (act as a fundamental data structure for our software to store information)

**Comment by gordonwky** [comment]
Problem have been resolved
