### ISSUE TITLE
SRS review for Xinyu (Domain Expert)

### ISSUE THREAD

**Issue by gordonwky** [gordonwky/GMM_EM#3]
@lele0007 
Here is the [SRS](https://github.com/gordonwky/GMM_EM/blob/886100bf4d484a3e241207968d7bd1af96f67011/docs/SRS/cas741_SRS.pdf)

**Comment by lele0007** [comment]
I write some comments on the document.
[Review_cas741_SRS.pdf](https://github.com/gordonwky/GMM_EM/files/14203268/Review_cas741_SRS.pdf)

**Comment by smiths** [comment]
Since the review is done, we can close this issue.  @gordonwky you should address the feedback from @lele0007.  You may wish to create separate issue based on the feedback.
