### ISSUE TITLE
Abbreviations and Acronyms

### ISSUE THREAD

**Issue by vgvreug** [gordonwky/GMM_EM#5]
[This](https://github.com/gordonwky/GMM_EM/blob/886100bf4d484a3e241207968d7bd1af96f67011/docs/SRS/main.tex#L211) line and [this](https://github.com/gordonwky/GMM_EM/blob/886100bf4d484a3e241207968d7bd1af96f67011/docs/SRS/main.tex#L219) line should be deleted so they don't show up in the pdf.

**Comment by gordonwky** [comment]
Solved
