### ISSUE TITLE
Scope and intended reader characteristics

### ISSUE THREAD

**Issue by vgvreug** [gordonwky/GMM_EM#6]
The first two sentences of Sec 2.2 are worded in a way that makes them a bit awkward to read. Here are a few suggestions of changes that I think might help:
- "in implementation of" -> "that implements the"
- "focus in" -> "focus on"
- Either add "the" before "clustering problem" or make "problem" plural, whichever is more appropriate
- "will limit to deal" -> "will only deal"
- remove "any"
- "dataset with only real-valued number" -> "datasets that solely contain real numbers"
- make "value" at the end of the sentence plural

In [this](https://github.com/gordonwky/GMM_EM/blob/886100bf4d484a3e241207968d7bd1af96f67011/docs/SRS/main.tex#L256) line "suffix" should be "satisfy" or "fulfill".

**Comment by gordonwky** [comment]
Solved
